baseurl = "http://wts.dgnest.com/"
languageCode = "en-us"
title = "What The $hell"
author = "Oscar Giraldo Castillo"
canonifyurls = true
paginate = 10
pygmentsuseclasses = true

[permalinks]
  post = "/:year/:month/:slug/"
